package io.kyros.content.afkzone;

import io.kyros.content.item.lootable.LootRarity;
import io.kyros.model.Items;
import io.kyros.model.definitions.ItemDef;
import io.kyros.model.entity.player.Player;
import io.kyros.model.items.GameItem;
import io.kyros.util.Misc;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class T0 {
    private static final Map<LootRarity, List<GameItem>> items = new HashMap<>();

    static {
        items.put(LootRarity.COMMON, Arrays.asList(
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7936, 25),
                new GameItem(536, 5),
                new GameItem(Items.SUPERIOR_DRAGON_BONES, 10),
                new GameItem(Items.MAGIC_LOGS_NOTED, 50),
                new GameItem(10833, 1),
                new GameItem(7478, 1),
                new GameItem(691, 1),
                new GameItem(7478, 1),
                new GameItem(691, 1)
        ));

        items.put(LootRarity.VERY_RARE, Arrays.asList(
                new GameItem(2722, 1),
                new GameItem(2572, 1),
                new GameItem(2528,1),//xp lamp
                new GameItem(696, 1),//250k Foundry
                new GameItem(6199, 1),//Mbox
                new GameItem(7774, 1)//100 Credits
                ));
    }
    private static GameItem commonChestRewards() {
        List<GameItem> itemList = Misc.random(10000) <= 9999 ? items.get(LootRarity.COMMON) : items.get(LootRarity.VERY_RARE);
        return Misc.getRandomItem(itemList);
    }

    public static void rolledCommon(Player c) {
        GameItem commonreward = commonChestRewards();
        c.getItems().addItemUnderAnyCircumstance(commonreward.getId(), commonreward.getAmount());
    }

    public Map<LootRarity, List<GameItem>> getLoot() {
        return items;
    }

    public static void main(String[] args) throws Exception {
        ItemDef.load();
        HashMap<GameItem, Integer> map = new HashMap<>();

        for (int i = 0; i < 720000; i++) {
            GameItem gameItem = commonChestRewards();
            int amount = map.getOrDefault(gameItem, 0);
            map.put(gameItem, amount + 1);
        }

        map.forEach((gameItem, amount) -> {
            String dropChance = String.format("%.2f", ((double) amount / 720000) * 100);
            String itemName = ItemDef.forId(gameItem.getId()).getName();
            System.out.println("Rolled a " + itemName + " " + amount + " times. " + dropChance);
        });

    }

}
