package io.kyros.sql.MainSql;

/**
 * @author ArkCane
 * @social Discord: ArkCane
 * Website: www.arkcane.net
 * @since 09/03/2024
 */
public enum SQLTable {

    ANNOUNCEMENT,

    SAVES_STARTERS,
    SAVES_PUNISHMENTS,
    SAVES_HISCORES,
    SAVES_REDEEMS,
    SAVES_WALLET_CODES,

    STATISTICS_TOP_DONATORS,
    STATISTICS_TOP_PKERS,
    STATISTICS_TOP_VOTERS,
    STATISTICS_ONLINE,

    DAILY_TRACKER,

    LOGS_TRADED_ITEMS,
    LOGS_STAKED_ITEMS,
    LOGS_AUCTION_POSTS,
    LOGS_AUCTION_COLLECTIONS,
    LOGS_AUCTION_PURCHASES,
    LOGS_AUCTION_BIDS,
    LOGS_AUCTION_CLEAR,
    LOGS_DROPPED_ITEMS,
    LOGS_PICKUP_ITEMS,
    LOGS_CONNECTIONS,
    LOGS_COMMANDS,
    LOGS_GLOBAL_EVENTS,
    LOGS_SHOP_SELLS,
    LOGS_SHOP_PURCHASES,
    LOGS_DEATH_ITEMS_LOST,
    LOGS_SUSPICIOUS_LOGINS,
    LOGS_GLOBAL_STATISTICS,
    LOGS_PUNISHMENTS,
    LOGS_PRIVATE_MESSAGES,
    LOGS_PUBLIC_CHAT,
    LOGS_FLOWER_PLANTS,
    LOGS_DICE_ROLLS,
    LOGS_NPC_GAMBLER,
    LOGS_YELL_MESSAGES,
    LOGS_CLAN_MESSAGES,
    LOGS_RARE_LOOT,
    LOGS_REFERRAL_CODES,
    LOGS_SOCIAL_CODES,
    LOGS_STORE_CLAIMS,
    LOGS_INTRODUCTION_CLAIMS,
    LOGS_VOTED,
    LOGS_YOUTUBE_COMMENTS,
    LOGS_CREATION,

    LOGS_REFUND_WALLET_CLAIMS,

    DATA_PLAYER_PROGRESS,
    DATA_REFERRAL_CODES,
    DATA_SOCIAL_CODES,
    DATA_YOUTUBE_VIDEOS,

    STORE_TRANSACTIONS,

    FORUMS_TOPICS,

    STORE_ITEMS,

    LOGS_BOSS_DEATHS,
    LOGS_PRICE_CHANGES,

    SAVES_LOGIN_REWARDS,
    SAVES_FREE_ITEMS,

    REALM_REFUND_WALLETS,

    LOGS_POS_LISTINGS,
    LOGS_POS_PURCHASES,

    TRANSFERS,
    REALM_TRANSFER_WALLETS,

    LOGS_ALERTS,
    LOGS_BUGS,

    PHONE_NUMBERS,
    STORE_PAYMENTS,
    PAYMENTS,
    CENTURION_CODES,
    FINALIZED_VOTES,
    CONFIRMED_VOTES,
    ITEM_PRICES,
    SERVERS,
    WEEKLY_ACTIVITY,

    DATA_REWARD_CODES,

    LOGS_REWARD_CODES,
    SERVER_UPDATES,
    STORE_OFFER_CLAIMS,
    EMPTY_ITEM,
    DISSOLVED_ITEM,
    LOGS_POS_CLAIMED_MONEY,
    VARIABLE_BOSS_LOG,

    WEBSITE_REFERRALS,
    WEBSITE_REFERRAL_JOINS,
    WEBSITE_REFERRAL_PAYMENTS,
    WEBSITE_REFERRAL_1HR,

    DAILY_DEAL_CLAIM_LOG,

    CAMPAIGN_LOG,
    SEASON_PASS,

    BOSS_UNLOCK_LOG,
    ITEM_TRANSFER,
    STAFF_VAULT_LOG,
    ;


    public static String GAME_SCHEMA = "game.";

    public static String EB_PAYMENT = "ebpayments.";

    public static String getGameSchemaTable(SQLTable entry) {
        return "arkcane_" + GAME_SCHEMA + entry.toTableName();
    }

    public static String getEbPaymentSchemaTable(SQLTable entry) {
        return EB_PAYMENT + entry.toTableName();
    }

    public String toTableName() {
        return name().toLowerCase();
    }
}

