package io.kyros.content.taskmaster;

public enum Tasks {
    //Easy
    BANDOS(10,"General Graardor", TaskDifficulty.EASY, TaskType.COMBAT, false, false),
    ZAMMY(10,"K'ril Tsutsaroth",TaskDifficulty.EASY, TaskType.COMBAT, false, false),
    SARA(10,"Commander Zilyana",TaskDifficulty.EASY, TaskType.COMBAT, false, false),
    ARMA(10,"Kree'arra",TaskDifficulty.EASY, TaskType.COMBAT, false, false),
    CORP(5,"Corporeal Beast",TaskDifficulty.EASY, TaskType.COMBAT, false, true),
    NIGHTMARE(5,"Nightmare",TaskDifficulty.EASY, TaskType.COMBAT, false, false),
    DAG_KINGS(15,"Dagannoth",TaskDifficulty.EASY, TaskType.COMBAT, false, false),
    KRAKEN(25,"Kraken",TaskDifficulty.EASY, TaskType.COMBAT, false, false),
    ZULRAH(10,"Zulrah",TaskDifficulty.EASY, TaskType.COMBAT, false, false),
    SARACHNIS(5,"Sarachnis",TaskDifficulty.EASY, TaskType.COMBAT, false, false),
    BARREL_CHEST(10,"Barrelchest",TaskDifficulty.EASY, TaskType.COMBAT, false, false),
    BARROWS_BROTHERS(30,"Barrows",TaskDifficulty.EASY, TaskType.COMBAT, false, false),
    MOLE(10,"Giant Mole",TaskDifficulty.EASY, TaskType.COMBAT, false, false),
    KQ(10,"Kalphite Queen",TaskDifficulty.EASY, TaskType.COMBAT, false, false),
    HYDRA(5,"Alchemical Hydra",TaskDifficulty.EASY, TaskType.COMBAT, false, false),
    CERB(10,"Cerberus",TaskDifficulty.EASY, TaskType.COMBAT, false, false),
    NEX(5,"Nex",TaskDifficulty.EASY, TaskType.COMBAT, false, false),

    ARAPHEL(5,"Araphel",TaskDifficulty.EASY, TaskType.COMBAT, false, true),
    VET_ION(10,"Vet'ion",TaskDifficulty.EASY, TaskType.COMBAT, false, true),
    CALLISTO(10,"Callisto",TaskDifficulty.EASY, TaskType.COMBAT, false, true),
    SCORPIA(10,"Scorpia",TaskDifficulty.EASY, TaskType.COMBAT, false, true),
    VENENATIS(10,"Venenatis",TaskDifficulty.EASY, TaskType.COMBAT, false, true),
    CHAOS_ELE(10,"Chaos elemental",TaskDifficulty.EASY, TaskType.COMBAT, false, true),
    CHAOS_FANATIC(10,"Chaos fanatic",TaskDifficulty.EASY, TaskType.COMBAT, false, true),
    CRAZY_ARCH(10,"Crazy archaeologist",TaskDifficulty.EASY, TaskType.COMBAT, false, true),
    KBD(10,"King Black Dragon",TaskDifficulty.EASY, TaskType.COMBAT, false, true),

    //Skilling
    PRAYER_POT(35,"Craft @whi@Prayer pot's",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    COMBAT_POTIONS(10,"Craft @whi@Combat Pot's",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    OAK_TREES(50,"Cut @whi@Oak Trees",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    WILLOW_TREES(50,"Cut @whi@Willow Trees",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    MAPLE_TREES(50,"Cut @whi@Maple Trees",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    YEW_TREES(50,"Cut @whi@Yew Trees",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    MAGIC_TREES(50,"Cut @whi@Magic Trees",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    BURN_LOGS(100,"Burn @whi@Logs",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    FLETCH_BOWS(50,"Fletch @whi@bows",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    BURY_BONES(50,"Bury @whi@bones",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    DRAGON_BONES(50,"Use @whi@Dragon bones(altar)",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    THIEVE_STALLS(75,"Steal from @whi@stalls",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    GROW_HERBS(50,"Grow @whi@Herbs",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    GROW_TORTOLS(35,"Grow @whi@Torstols",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    ROOFTOP_COURSES(10,"Complete @whi@Rooftop courses",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    CATCH_FISH(100,"Catch @whi@Fish",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    FISH_LOBSTERS(50,"Fish @whi@Lobsters",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    FISH_SHARK(50,"Fish @whi@Sharks",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    COOK_FISH(10,"Cook @whi@Fish",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    COOK_SWORDFISH(35,"Cook @whi@Swordfish",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    CUT_GEMS(100,"Cut @whi@Gems",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    CUT_DIAMONDS(50,"Cut @whi@Diamonds",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    CUT_DRAGONSTONE(35,"Cut @whi@Dragonstones",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    ZENYTE_JEWELRY(3,"Craft @whi@Zenyte jewelry",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    STRENGTH_AMULET(30,"Craft @whi@Strength amulets",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    FURY(3,"Craft @whi@Amulet of fury",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    MINE_ORES(100,"Mine @whi@Ores",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    SMELT_BARS(50,"Smelt @whi@Bars",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    SMELT_RUNE_BARS(25,"Smelt @whi@Rune Bars",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    MAKE_RUNES(500,"Make @whi@Runes",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    ANY_DHIDE(50,"Craft @whi@d'hide body",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    BLACK_DHIDE(25,"Craft @whi@Black d'hide body",TaskDifficulty.EASY, TaskType.SKILLING, false, true),
    BLACK_DHIDE_CHAPS(25,"Craft @whi@Black d'hide chaps",TaskDifficulty.EASY, TaskType.SKILLING, false, false),
    BLACK_DHIDE_VEMBRACES(25,"Craft @whi@Black d'hide vembraces",TaskDifficulty.EASY, TaskType.SKILLING, false, false),

    //MEDIUM
    BANDOS_1(50,"General Graardor", TaskDifficulty.MEDIUM, TaskType.COMBAT, false, false),
    ZAMMY_1(50,"K'ril Tsutsaroth",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, false),
    SARA_1(50,"Commander Zilyana",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, false),
    ARMA_1(50,"Kree'arra",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, false),
    CORP_1(25,"Corporeal Beast",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, true),
    NIGHTMARE_1(10,"Nightmare",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, false),
    DAG_KINGS_1(75,"Dagannoth",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, false),
    KRAKEN_1(75,"Kraken",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, false),
    ZULRAH_1(50,"Zulrah",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, false),
    SARACHNIS_1(25,"Sarachnis",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, false),
    BARREL_CHEST_1(50,"Barrelchest",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, false),
    BARROWS_BROTHERS_1(100,"Barrows",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, false),
    MOLE_1(75,"Giant Mole",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, false),
    KQ_1(25,"Kalphite Queen",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, false),
    HYDRA_1(15,"Alchemical Hydra",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, false),
    CERB_1(20,"Cerberus",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, false),
    NEX_1(10,"Nex",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, false),

    ARAPHEL_1(15,"Araphel",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, true),
    VET_ION_1(20,"Vet'ion",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, true),
    CALLISTO_1(20,"Callisto",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, true),
    SCORPIA_1(20,"Scorpia",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, true),
    VENENATIS_1(20,"Venenatis",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, true),
    CHAOS_ELE_1(20,"Chaos elemental",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, true),
    CHAOS_FANATIC_1(20,"Chaos fanatic",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, true),
    CRAZY_ARCH_1(20,"Crazy archaeologist",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, true),
    KBD_1(25,"King Black Dragon",TaskDifficulty.MEDIUM, TaskType.COMBAT, false, true),

    //Skilling
    PRAYER_POT_1(60,"Craft @whi@Prayer pot's",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    COMBAT_POTIONS_1(30,"Craft @whi@Combat Pot's",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    OAK_TREES_1(100,"Cut @whi@Oak Trees",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    WILLOW_TREES_1(100,"Cut @whi@Willow Trees",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    MAPLE_TREES_1(100,"Cut @whi@Maple Trees",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    YEW_TREES_1(100,"Cut @whi@Yew Trees",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    MAGIC_TREES_1(100,"Cut @whi@Magic Trees",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    BURN_LOGS_1(250,"Burn @whi@Logs",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    FLETCH_BOWS_1(100,"Fletch @whi@bows",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    BURY_BONES_1(100,"Bury @whi@bones",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    DRAGON_BONES_1(100,"Use @whi@Dragon bones(altar)",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    THIEVE_STALLS_1(150,"Steal from @whi@stalls",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    GROW_HERBS_1(100,"Grow @whi@Herbs",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    GROW_TORTOLS_1(60,"Grow @whi@Torstols",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    ROOFTOP_COURSES_1(25,"Complete @whi@Rooftop courses",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    CATCH_FISH_1(200,"Catch @whi@Fish",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    FISH_SHARK_1(100,"Fish @whi@Sharks",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    COOK_FISH_1(100,"Cook @whi@Fish",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    CUT_GEMS_1(100,"Cut @whi@Gems",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    CUT_DIAMONDS_1(100,"Cut @whi@Diamonds",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    CUT_DRAGONSTONE_1(100,"Cut @whi@Dragonstones",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    ZENYTE_JEWELRY_1(10,"Craft @whi@Zenyte jewelry",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    FURY_1(10,"Craft @whi@Amulet of fury",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    MINE_ORES_1(150,"Mine @whi@Ores",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    SMELT_BARS_1(100,"Smelt @whi@Bars",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    SMELT_RUNE_BARS_1(100,"Smelt @whi@Rune Bars",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    MAKE_RUNES_1(500,"Make @whi@Runes",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    ANY_DHIDE_1(100,"Craft @whi@d'hide body",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    BLACK_DHIDE_1(50,"Craft @whi@Black d'hide body",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, true),
    BLACK_DHIDE_CHAPS_1(50,"Craft @whi@Black d'hide chaps",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, false),
    BLACK_DHIDE_VEMBRACES_1(50,"Craft @whi@Black d'hide vembraces",TaskDifficulty.MEDIUM, TaskType.SKILLING, false, false),

    //HARD
    BANDOS_2(100,"General Graardor", TaskDifficulty.HARD, TaskType.COMBAT, false, false),
    ZAMMY_2(100,"K'ril Tsutsaroth",TaskDifficulty.HARD, TaskType.COMBAT, false, false),
    SARA_2(100,"Commander Zilyana",TaskDifficulty.HARD, TaskType.COMBAT, false, false),
    ARMA_2(100,"Kree'arra",TaskDifficulty.HARD, TaskType.COMBAT, false, false),
    CORP_2(50,"Corporeal Beast",TaskDifficulty.HARD, TaskType.COMBAT, false, true),
    NIGHTMARE_2(20,"Nightmare",TaskDifficulty.HARD, TaskType.COMBAT, false, false),
    DAG_KINGS_2(100,"Dagannoth",TaskDifficulty.HARD, TaskType.COMBAT, false, false),
    KRAKEN_2(100,"Kraken",TaskDifficulty.HARD, TaskType.COMBAT, false, false),
    ZULRAH_2(100,"Zulrah",TaskDifficulty.HARD, TaskType.COMBAT, false, false),
    SARACHNIS_2(50,"Sarachnis",TaskDifficulty.HARD, TaskType.COMBAT, false, false),
    BARREL_CHEST_2(100,"Barrelchest",TaskDifficulty.HARD, TaskType.COMBAT, false, false),
    BARROWS_BROTHERS_2(200,"Barrows",TaskDifficulty.HARD, TaskType.COMBAT, false, false),
    MOLE_2(100,"Giant Mole",TaskDifficulty.HARD, TaskType.COMBAT, false, false),
    KQ_2(50,"Kalphite Queen",TaskDifficulty.HARD, TaskType.COMBAT, false, false),
    HYDRA_2(25,"Alchemical Hydra",TaskDifficulty.HARD, TaskType.COMBAT, false, false),
    CERB_2(25,"Cerberus",TaskDifficulty.HARD, TaskType.COMBAT, false, false),
    NEX_2(10,"Nex",TaskDifficulty.HARD, TaskType.COMBAT, false, false),

    ARAPHEL_2(50,"Araphel",TaskDifficulty.HARD, TaskType.COMBAT, false, true),
    VET_ION_2(50,"Vet'ion",TaskDifficulty.HARD, TaskType.COMBAT, false, true),
    CALLISTO_2(50,"Callisto",TaskDifficulty.HARD, TaskType.COMBAT, false, true),
    SCORPIA_2(50,"Scorpia",TaskDifficulty.HARD, TaskType.COMBAT, false, true),
    VENENATIS_2(50,"Venenatis",TaskDifficulty.HARD, TaskType.COMBAT, false, true),
    CHAOS_ELE_2(50,"Chaos elemental",TaskDifficulty.HARD, TaskType.COMBAT, false, true),
    CHAOS_FANATIC_2(50,"Chaos fanatic",TaskDifficulty.HARD, TaskType.COMBAT, false, true),
    CRAZY_ARCH_2(50,"Crazy archaeologist",TaskDifficulty.HARD, TaskType.COMBAT, false, true),
    KBD_2(100,"King Black Dragon",TaskDifficulty.HARD, TaskType.COMBAT, false, true),
    //Skilling
    COMBAT_POTIONS_2(50,"Craft @whi@Combat Pot's",TaskDifficulty.HARD, TaskType.SKILLING, false, true),
    MAGIC_TREES_2(250,"Cut @whi@Magic Trees",TaskDifficulty.HARD, TaskType.SKILLING, false, true),
    BURN_LOGS_2(500,"Burn @whi@Logs",TaskDifficulty.HARD, TaskType.SKILLING, false, true),
    FLETCH_BOWS_2(250,"Fletch @whi@bows",TaskDifficulty.HARD, TaskType.SKILLING, false, true),
    DRAGON_BONES_2(250,"Use @whi@Dragon bones(altar)",TaskDifficulty.HARD, TaskType.SKILLING, false, true),
    THIEVE_STALLS_2(200,"Steal from @whi@stalls",TaskDifficulty.HARD, TaskType.SKILLING, false, true),
    GROW_TORTOLS_2(100,"Grow @whi@Torstols",TaskDifficulty.HARD, TaskType.SKILLING, false, true),
    ROOFTOP_COURSES_2(50,"Complete @whi@Rooftop courses",TaskDifficulty.HARD, TaskType.SKILLING, false, true),
    FISH_SHARK_2(250,"Fish @whi@Sharks",TaskDifficulty.HARD, TaskType.SKILLING, false, true),
    COOK_FISH_2(250,"Cook @whi@Fish",TaskDifficulty.HARD, TaskType.SKILLING, false, true),
    CUT_GEMS_2(250,"Cut @whi@Gems",TaskDifficulty.HARD, TaskType.SKILLING, false, true),
    ZENYTE_JEWELRY_2(20,"Craft @whi@Zenyte jewelry",TaskDifficulty.HARD, TaskType.SKILLING, false, true),
    FURY_2(20,"Craft @whi@Amulet of fury",TaskDifficulty.HARD, TaskType.SKILLING, false, true),
    MINE_ORES_2(250,"Mine @whi@Ores",TaskDifficulty.HARD, TaskType.SKILLING, false, true),
    SMELT_RUNE_BARS_2(200,"Smelt @whi@Rune Bars",TaskDifficulty.HARD, TaskType.SKILLING, false, true),
    MAKE_RUNES_2(1000,"Make @whi@Runes",TaskDifficulty.HARD, TaskType.SKILLING, false, true),
    ANY_DHIDE_2(150,"Craft @whi@d'hide body",TaskDifficulty.HARD, TaskType.SKILLING, false, true),
    BLACK_DHIDE_2(100,"Craft @whi@Black d'hide body",TaskDifficulty.HARD, TaskType.SKILLING, false, true),
    BLACK_DHIDE_CHAPS_2(100,"Craft @whi@Black d'hide chaps",TaskDifficulty.HARD, TaskType.SKILLING, false, false),
    BLACK_DHIDE_VEMBRACES_2(100,"Craft @whi@Black d'hide vembraces",TaskDifficulty.HARD, TaskType.SKILLING, false, false),

    //ELITE
    BANDOS_3(150,"General Graardor", TaskDifficulty.ELITE, TaskType.COMBAT, false, false),
    ZAMMY_3(150,"K'ril Tsutsaroth",TaskDifficulty.ELITE, TaskType.COMBAT, false, false),
    SARA_3(150,"Commander Zilyana",TaskDifficulty.ELITE, TaskType.COMBAT, false, false),
    ARMA_3(150,"Kree'arra",TaskDifficulty.ELITE, TaskType.COMBAT, false, false),
    CORP_3(75,"Corporeal Beast",TaskDifficulty.ELITE, TaskType.COMBAT, false, true),
    NIGHTMARE_3(25,"Nightmare",TaskDifficulty.ELITE, TaskType.COMBAT, false, false),
    DAG_KINGS_3(200,"Dagannoth",TaskDifficulty.ELITE, TaskType.COMBAT, false, false),
    KRAKEN_3(250,"Kraken",TaskDifficulty.ELITE, TaskType.COMBAT, false, false),
    ZULRAH_3(100,"Zulrah",TaskDifficulty.ELITE, TaskType.COMBAT, false, false),
    SARACHNIS_3(75,"Sarachnis",TaskDifficulty.ELITE, TaskType.COMBAT, false, false),
    BARREL_CHEST_3(150,"Barrelchest",TaskDifficulty.ELITE, TaskType.COMBAT, false, false),
    BARROWS_BROTHERS_3(300,"Barrows",TaskDifficulty.ELITE, TaskType.COMBAT, false, false),
    MOLE_3(150,"Giant Mole",TaskDifficulty.ELITE, TaskType.COMBAT, false, false),
    KQ_3(75,"Kalphite Queen",TaskDifficulty.ELITE, TaskType.COMBAT, false, false),
    HYDRA_3(75,"Alchemical Hydra",TaskDifficulty.ELITE, TaskType.COMBAT, false, false),
    CERB_3(25,"Cerberus",TaskDifficulty.ELITE, TaskType.COMBAT, false, false),
    NEX_3(10,"Nex",TaskDifficulty.ELITE, TaskType.COMBAT, false, false),

    ARAPHEL_3(75,"Araphel",TaskDifficulty.ELITE, TaskType.COMBAT, false, true),
    VET_ION_3(75,"Vet'ion",TaskDifficulty.ELITE, TaskType.COMBAT, false, true),
    CALLISTO_3(75,"Callisto",TaskDifficulty.ELITE, TaskType.COMBAT, false, true),
    SCORPIA_3(75,"Scorpia",TaskDifficulty.ELITE, TaskType.COMBAT, false, true),
    VENENATIS_3(75,"Venenatis",TaskDifficulty.ELITE, TaskType.COMBAT, false, true),
    CHAOS_ELE_3(75,"Chaos elemental",TaskDifficulty.ELITE, TaskType.COMBAT, false, true),
    CHAOS_FANATIC_3(75,"Chaos fanatic",TaskDifficulty.ELITE, TaskType.COMBAT, false, true),
    CRAZY_ARCH_3(75,"Crazy archaeologist",TaskDifficulty.ELITE, TaskType.COMBAT, false, true),
    KBD_3(150,"King Black Dragon",TaskDifficulty.ELITE, TaskType.COMBAT, false, true),


    //daily
    ARMA_4(300,"Kree'arra",TaskDifficulty.MEDIUM, TaskType.COMBAT, true, false),
    ZAMMY_4(300,"K'ril Tsutsaroth",TaskDifficulty.HARD, TaskType.COMBAT, true, false),
    BANDOS_4(300,"General Graardor", TaskDifficulty.MEDIUM, TaskType.COMBAT, true, false),
    SARA_4(300,"Commander Zilyana",TaskDifficulty.MEDIUM, TaskType.COMBAT, true, false),
    CORP_4(300,"Corporeal Beast",TaskDifficulty.HARD, TaskType.COMBAT, true, true),
    NIGHTMARE_4(100,"Nightmare",TaskDifficulty.HARD, TaskType.COMBAT, true, false),
    JADS(25,"TzTok-Jad",TaskDifficulty.EASY, TaskType.COMBAT, true, true),
    INFERNAL(25,"Inferno",TaskDifficulty.MEDIUM, TaskType.COMBAT, true, false),
    ZULRAH_4(200,"Zulrah",TaskDifficulty.MEDIUM, TaskType.COMBAT, true, false),
    BARROWS_BROTHERS_4(500,"Barrows",TaskDifficulty.EASY, TaskType.COMBAT, true, true),
    SARACHNIS_4(200,"Sarachnis",TaskDifficulty.EASY, TaskType.COMBAT, true, false),
    KQ_4(200,"Kalphite Queen",TaskDifficulty.MEDIUM, TaskType.COMBAT, true, false),
    COX(50,"Chambers",TaskDifficulty.MEDIUM, TaskType.COMBAT, true, false),
    NEX_4(300,"Nex",TaskDifficulty.ELITE, TaskType.COMBAT, true, false),
    CERB_4(200,"Cerberus",TaskDifficulty.MEDIUM, TaskType.COMBAT, true, false),
    TOB(50,"Theatre Of Blood",TaskDifficulty.HARD, TaskType.COMBAT, true, false),
    HYDRA_4(150,"Alchemical Hydra",TaskDifficulty.ELITE, TaskType.COMBAT, true, false),

    ARAPHEL_4(150,"Araphel",TaskDifficulty.ELITE, TaskType.COMBAT, true, true),
    VET_ION_4(150,"Vet'ion",TaskDifficulty.ELITE, TaskType.COMBAT, true, true),
    CALLISTO_4(150,"Callisto",TaskDifficulty.ELITE, TaskType.COMBAT, true, true),
    SCORPIA_4(150,"Scorpia",TaskDifficulty.ELITE, TaskType.COMBAT, true, true),
    VENENATIS_4(150,"Venenatis",TaskDifficulty.ELITE, TaskType.COMBAT, true, true),
    CHAOS_ELE_4(150,"Chaos elemental",TaskDifficulty.ELITE, TaskType.COMBAT, true, true),
    CHAOS_FANATIC_4(150,"Chaos fanatic",TaskDifficulty.ELITE, TaskType.COMBAT, true, true),
    CRAZY_ARCH_4(150,"Crazy archaeologist",TaskDifficulty.ELITE, TaskType.COMBAT, true, true),
    KBD_4(300,"King Black Dragon",TaskDifficulty.ELITE, TaskType.COMBAT, true, true);




    public final int max;
    public final String desc;
    public final boolean daily;
    public final boolean wildy;
    public final TaskDifficulty difficultyType;
    public final TaskType taskType;

    Tasks(int max, String desc, TaskDifficulty difficultyType, TaskType taskType, boolean daily, boolean wildy) {
        this.max = max;
        this.desc = desc;
        this.daily = daily;
        this.difficultyType = difficultyType;
        this.taskType = taskType;
        this.wildy = wildy;
    }
}
